<?php


/** autoload.php @generated by Composer */
require_once __DIR__.'/composer/vendor/autoload.php';
require_once __DIR__.'/config.php';



/** Start application process */
new App\Application();





