<?php


/** autoload.php @generated by Composer */
require_once __DIR__.'/composer/vendor/autoload.php';
require_once __DIR__.'/config.php';


date_default_timezone_set("Asia/Tehran");
/** Start application process */
new App\Application();




